# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ dev ]
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: notify-microsoft-teams
      uses: Skitionek/notify-microsoft-teams@v1.0.4
      with:
        if: always()
        webhook_url: 'https://capgemini.webhook.office.com/webhookb2/ce3a40ff-7a0d-499b-bbea-30251888b498@76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61/JenkinsCI/f357ef651c4b4617bf87d33ff0d07fd5/75c7a99d-2161-4462-89c5-f762ef1e1150'
        job: ${{ toJson(job) }}
